# Generated by Django 5.2 on 2026-05-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='case',
            new_name='cases_case_is_acti_033994_idx',
            old_name='cases_active_order_idx',
        ),
        migrations.AlterField(
            model_name='case',
            name='body',
            field=models.TextField(blank=True, help_text='Полный текст кейса для страницы подробностей. Можно использовать двойные переносы для абзацев.'),
        ),
        migrations.AlterField(
            model_name='case',
            name='company_name',
            field=models.CharField(blank=True, help_text='Название компании-клиента (публично — по согласию)', max_length=200),
        ),
        migrations.AlterField(
            model_name='case',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Обложка кейса — показывается на детальной странице', null=True, upload_to='cases/covers/'),
        ),
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='case',
            name='industry',
            field=models.CharField(blank=True, help_text='Ритейл / IT / Производство / …', max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='logo',
            field=models.ImageField(blank=True, help_text='Логотип (SVG или PNG с прозрачным фоном). 200–400px по большей стороне', null=True, upload_to='cases/logos/'),
        ),
        migrations.AlterField(
            model_name='case',
            name='metric',
            field=models.CharField(blank=True, help_text='Крупная цифра: «+15%», «×2», «−30 дней»', max_length=60),
        ),
        migrations.AlterField(
            model_name='case',
            name='metric_label',
            field=models.CharField(blank=True, help_text='Расшифровка метрики: «маржинальности», «скорость найма»', max_length=120),
        ),
        migrations.AlterField(
            model_name='case',
            name='order',
            field=models.IntegerField(default=0, help_text='Порядок отображения на лендинге (меньше — выше)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='short_text',
            field=models.TextField(blank=True, help_text='Краткое описание на карточке на лендинге (2–3 предложения)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-идентификатор. Пример: retail-margin-uplift. Оставьте пустым — сгенерируется из заголовка.', max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Короткое описание, строка под заголовком на карточке', max_length=400),
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(help_text='Заголовок кейса, например «Рост маржи розничной сети»', max_length=200),
        ),
    ]
