# Generated by Django 5.2 on 2026-05-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='blog_blogpo_is_publ_1eae91_idx',
            old_name='blog_blogpost_pub_order',
        ),
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='blog_blogpo_categor_481d67_idx',
            old_name='blog_blogpost_cat',
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(blank=True, help_text='Полный текст статьи. Двойной перенос — новый абзац. Поддерживается простой текст; HTML-теги отображаются как символы.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Обложка для карточки и страницы статьи (рекомендация 1600×900).', null=True, upload_to='blog/covers/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Краткое описание (1–2 предложения), показывается на карточке лендинга и в превью статьи.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Опубликовать статью. Не отмечайте — пока готовите черновик.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='order',
            field=models.IntegerField(default=0, help_text='Порядок отображения на лендинге (меньше — раньше). При равных — по дате публикации.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='reading_time_min',
            field=models.PositiveIntegerField(default=5, help_text='Время чтения в минутах (для подписи на карточке).'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-идентификатор. Генерируется из заголовка автоматически.', max_length=200, unique=True),
        ),
    ]
