# Generated by Django 6.0.2 on 2026-04-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(help_text="Unique block identifier, e.g. 'hero_title'", max_length=100, unique=True)),
                ('title', models.CharField(help_text='Human-readable label for admin', max_length=255)),
                ('content', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('text', 'Текст'), ('html', 'HTML')], default='text', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Контент-блок',
                'verbose_name_plural': 'Контент-блоки',
                'ordering': ['key'],
            },
        ),
    ]
