# Generated by Django 5.2 on 2026-05-28 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_reset_expensive_model'),
        ('submissions', '0006_rename_submission_invite_t_idx_submissions_invite__3cf734_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='ai_chatmess_session_d95756_idx',
            old_name='ai_chatmsg_session_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='ai_chatsess_status_d5b04e_idx',
            old_name='ai_chatsess_status_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='ai_chatsess_client__6dcd43_idx',
            old_name='ai_chatsess_client_idx',
        ),
        migrations.AlterField(
            model_name='aiassistantconfig',
            name='greeting',
            field=models.TextField(help_text='Первое сообщение ассистента при открытии чата'),
        ),
        migrations.AlterField(
            model_name='aiassistantconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aiassistantconfig',
            name='max_tokens',
            field=models.PositiveIntegerField(default=800, help_text='Максимальная длина ответа ассистента в токенах'),
        ),
        migrations.AlterField(
            model_name='aiassistantconfig',
            name='model',
            field=models.CharField(default='gpt-4o-mini', help_text='Модель OpenAI (gpt-4o-mini / gpt-4o / gpt-4-turbo)', max_length=60),
        ),
        migrations.AlterField(
            model_name='aiassistantconfig',
            name='name',
            field=models.CharField(default='Baqsy AI', help_text='Имя ассистента, показывается в шапке чата', max_length=100),
        ),
        migrations.AlterField(
            model_name='aiassistantconfig',
            name='quick_replies',
            field=models.JSONField(blank=True, default=list, help_text='Кнопки быстрых ответов под приветствием. Формат: [{"label": "Хочу аудит", "payload": "Расскажи про аудит"}, …]'),
        ),
        migrations.AlterField(
            model_name='aiassistantconfig',
            name='system_prompt',
            field=models.TextField(help_text='Системный промпт. Описывает личность ассистента, правила, тон общения. Доступны плейсхолдеры: {{name}}, {{company}}, {{industry}} — будут подставлены, если данные уже собраны.'),
        ),
        migrations.AlterField(
            model_name='aiassistantconfig',
            name='tariff_prompt',
            field=models.TextField(blank=True, default='Если клиент готов к оплате, предложи перейти к выбору тарифа. Упомяни две опции: Ashıde 1 (базовый, 45 000 ₸) и Ashıde 2 (полный, 135 000 ₸). Не давай технических деталей оплаты — просто предложи нажать кнопку «Выбрать тариф».', help_text='Дополнительная инструкция для момента, когда нужно перейти к оплате'),
        ),
        migrations.AlterField(
            model_name='aiassistantconfig',
            name='temperature',
            field=models.FloatField(default=0.5, help_text='0.0–2.0. Чем выше — тем креативнее, но менее предсказуемо'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='collected_data',
            field=models.JSONField(blank=True, default=dict, help_text='Структурированные данные, собранные ассистентом: name, company, phone_wa, city, industry_code, goals'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='mode',
            field=models.CharField(choices=[('chat', 'Свободный диалог с AI'), ('questionnaire', 'Анкета (по одному вопросу)')], default='chat', help_text='Режим чата: свободный диалог или пошаговая анкета.', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='submission',
            field=models.ForeignKey(blank=True, help_text='Привязанная заявка — появляется после оплаты и запуска анкеты.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='submissions.submission'),
        ),
    ]
