# Generated by Django 6.0.2 on 2026-04-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('failed', 'Ошибка')], default='queued', max_length=20)),
                ('external_id', models.CharField(blank=True, help_text='External message/delivery ID', max_length=255)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Лог доставки',
                'verbose_name_plural': 'Логи доставки',
                'ordering': ['-created_at'],
            },
        ),
    ]
