# Generated by Django 6.0.2 on 2026-04-16 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Отрасль',
                'verbose_name_plural': 'Отрасли',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='industries.industry')),
            ],
            options={
                'verbose_name': 'Шаблон анкеты',
                'verbose_name_plural': 'Шаблоны анкет',
                'ordering': ['industry', '-version'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('field_type', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('choice', 'Выбор одного'), ('multichoice', 'Множественный выбор')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, default=dict, help_text='Options for choice/multichoice fields')),
                ('required', models.BooleanField(default=True)),
                ('block', models.CharField(choices=[('A', 'Блок А — Технический паспорт'), ('B', 'Блок Б — Содержательная часть'), ('C', 'Блок В — Глубокое сканирование')], default='A', max_length=1)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='industries.questionnairetemplate')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['template', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='questionnairetemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('industry',), name='one_active_template_per_industry'),
        ),
        migrations.AlterUniqueTogether(
            name='questionnairetemplate',
            unique_together={('industry', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('template', 'order')},
        ),
    ]
