# Generated by Django 5.2 on 2026-05-28 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0003_audit_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditparameter',
            name='code',
            field=models.SlugField(help_text="Машинный идентификатор параметра, например 'finance' или 'team-quality'.", max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='auditparameter',
            name='description',
            field=models.TextField(blank=True, help_text='Что именно анализирует этот параметр. Видит только админ.'),
        ),
        migrations.AlterField(
            model_name='auditparameter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auditparameter',
            name='model',
            field=models.CharField(default='gpt-4o-mini', help_text='Модель OpenAI для этого параметра.', max_length=60),
        ),
        migrations.AlterField(
            model_name='auditparameter',
            name='name',
            field=models.CharField(help_text='Человекочитаемое название: «Финансы», «Команда», «Маркетинг» и т.д.', max_length=120),
        ),
        migrations.AlterField(
            model_name='auditparameter',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок параметра в финальном отчёте (меньше — раньше).'),
        ),
        migrations.AlterField(
            model_name='auditparameter',
            name='system_prompt',
            field=models.TextField(help_text='System-prompt для AI-ассистента, который анализирует ответы по этому параметру. Описывает роль ассистента, фокус анализа, тон и структуру вывода. Доступны плейсхолдеры: {{name}}, {{company}}, {{industry}}, {{answers}} — последний автоматически подставляется списком ответов клиента.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='condition_question',
            field=models.ForeignKey(blank=True, help_text='Родительский вопрос. Если указан, текущий вопрос будет показан только при совпадении ответа с одним из «Значений для показа».', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_questions', to='industries.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='condition_values',
            field=models.JSONField(blank=True, default=list, help_text='Список значений: вопрос показывается, если ответ на родительский ∈ список. Пример: <code>["Владелец / Совладелец", "Топ-менеджер"]</code>'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text='Варианты для choice/multichoice. Формат: <code>{"choices": ["Вариант 1", "Вариант 2", "Вариант 3"]}</code>'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(help_text='Порядковый номер внутри анкеты (меньше — раньше)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='parameter',
            field=models.ForeignKey(blank=True, help_text='К какому параметру аудита относится вопрос. Используется при формировании раздела отчёта соответствующим AI-ассистентом.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='industries.auditparameter'),
        ),
        migrations.AlterField(
            model_name='question',
            name='placeholder',
            field=models.CharField(blank=True, default='', help_text='Подсказка для поля ввода (не обязательна)', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='stage',
            field=models.CharField(blank=True, default='', help_text='Название этапа для группировки в админке и в чате. Примеры: «Этап I: Паспорт компании», «Блок II: Менеджер».', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='Формулировка вопроса (увидит клиент)'),
        ),
        migrations.AlterField(
            model_name='questionnairetemplate',
            name='completion_text',
            field=models.TextField(blank=True, default='Спасибо, {{name}}! Анкета завершена. Наш эксперт разберёт ответы и пришлёт именной PDF-отчёт в WhatsApp в течение 3–5 рабочих дней.', help_text='Текст в чате ПОСЛЕ последнего вопроса (благодарность + ETA доставки). Плейсхолдеры {{name}}, {{company}}, {{total}}.'),
        ),
        migrations.AlterField(
            model_name='questionnairetemplate',
            name='intro_text',
            field=models.TextField(blank=True, default='Сейчас я задам вам {{total}} вопросов. Займёт около 20 минут. Можно прерываться и возвращаться — прогресс сохраняется.', help_text='Вводный текст в чате ПЕРЕД первым вопросом анкеты. Поддерживает плейсхолдеры {{name}}, {{company}}, {{total}} — подставятся автоматически. Это именно тот текст, который клиент видит на скриншоте «Сейчас я задам вам N вопросов…».'),
        ),
    ]
