# Generated by Django 6.0.2 on 2026-04-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='last_reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
