# Generated by Django 6.0.2 on 2026-04-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submission_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='answer',
            new_name='submissions_submiss_7df7c8_idx',
            old_name='answers_submission_question_idx',
        ),
        migrations.RenameIndex(
            model_name='submission',
            new_name='submissions_client__f31474_idx',
            old_name='submissions_client_created_idx',
        ),
        migrations.RenameIndex(
            model_name='submission',
            new_name='submissions_status_c2b4f2_idx',
            old_name='submissions_status_idx',
        ),
        migrations.RenameIndex(
            model_name='submission',
            new_name='submissions_status_fa968c_idx',
            old_name='submissions_status_created_idx',
        ),
    ]
