# Generated by Django 5.2 on 2026-05-28 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_audit_group_participant'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditparticipant',
            new_name='submissions_invite__3cf734_idx',
            old_name='submission_invite_t_idx',
        ),
        migrations.RenameIndex(
            model_name='auditparticipant',
            new_name='submissions_status_cf436b_idx',
            old_name='submission_part_status_idx',
        ),
        migrations.AlterField(
            model_name='auditgroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auditgroup',
            name='invitation_text',
            field=models.TextField(blank=True, help_text='Текст приглашения, который рассылается участникам. Если пусто — используется дефолт.'),
        ),
        migrations.AlterField(
            model_name='auditgroup',
            name='quorum_size',
            field=models.PositiveSmallIntegerField(help_text='Количество участников, выбранное инициатором (3–7).'),
        ),
        migrations.AlterField(
            model_name='auditparticipant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auditparticipant',
            name='invite_token',
            field=models.CharField(help_text='UUID4 hex без дефисов, используется в ссылке /invite/<token>.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='auditparticipant',
            name='submission',
            field=models.ForeignKey(blank=True, help_text='Привязанный Submission участника. Создаётся при первом ответе. Содержит его собственные ответы.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_records', to='submissions.submission'),
        ),
    ]
