# Generated by Django 6.0.2 on 2026-04-16 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_text', models.TextField(blank=True, help_text='Текст аудита от администратора')),
                ('pdf_url', models.URLField(blank=True, help_text='MinIO presigned URL to PDF')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утверждён'), ('sent', 'Отправлен')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='submissions.submission')),
            ],
            options={
                'verbose_name': 'Аудит-отчёт',
                'verbose_name_plural': 'Аудит-отчёты',
            },
        ),
    ]
