# Generated by Django 6.0.2 on 2026-04-16 05:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(help_text='CloudPayments TransactionId', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('succeeded', 'Успешно'), ('failed', 'Ошибка'), ('refunded', 'Возврат')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('currency', models.CharField(default='KZT', max_length=3)),
                ('raw_webhook', models.JSONField(blank=True, default=dict, help_text='Raw CloudPayments webhook payload')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('price_kzt', models.DecimalField(decimal_places=0, help_text='Цена в тенге', max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['price_kzt'],
            },
        ),
    ]
