# Generated by Django 6.0.2 on 2026-04-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_submiss_491d62_idx',
            old_name='payments_submission_created_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_status_7ad4af_idx',
            old_name='payments_status_idx',
        ),
    ]
